@file:Suppress("SpellCheckingInspection")

package atlas.graphviz.internal

import atlas.core.internal.InternalPropertiesSpec
import atlas.core.internal.PropertiesSpecImpl
import atlas.core.internal.bool
import atlas.core.internal.enum
import atlas.core.internal.float
import atlas.core.internal.int
import atlas.core.internal.number
import atlas.core.internal.string
import atlas.graphviz.ArrowType
import atlas.graphviz.ClusterAttributes
import atlas.graphviz.ClusterMode
import atlas.graphviz.Dir
import atlas.graphviz.EdgeAttributes
import atlas.graphviz.EdgeStyle
import atlas.graphviz.GraphAttributes
import atlas.graphviz.ImagePos
import atlas.graphviz.LayoutEngine
import atlas.graphviz.NodeAttributes
import atlas.graphviz.NodeStyle
import atlas.graphviz.RankDir
import atlas.graphviz.Shape
import atlas.graphviz.SmoothType
import org.gradle.api.model.ObjectFactory
import org.gradle.api.provider.ProviderFactory

internal class NodeAttributesImpl(objects: ObjectFactory, providers: ProviderFactory) :
  NodeAttributes,
  InternalPropertiesSpec by PropertiesSpecImpl(objects, providers, "atlas.graphviz.node") {
  override var lineColor by string("color")
  override var colorScheme by string("colorscheme")
  override var comment by string("comment")
  override var distortion by string("distortion")
  override var fillColor by string("fillcolor")
  override var fixedSize by string("fixedsize")
  override var fontColor by string("fontcolor")
  override var fontName by string("fontname")
  override var fontSize by string("fontsize")
  override var gradientAngle by int("gradientangle")
  override var group by string("group")
  override var height by number("height")
  override var href by string("href")
  override var id by string("id")
  override var image by string("image")
  override var imagePos by enum<ImagePos>("imagepos")
  override var imageScale by string("imagescale")
  override var label by string("label")
  override var labelLoc by string("labelloc")
  override var layer by string("layer")
  override var margin by string("margin")
  override var noJustify by bool("nojustify")
  override var ordering by string("ordering")
  override var orientation by number("orientation")
  override var penWidth by number("penwidth")
  override var peripheries by int("peripheries")
  override var pin by bool("pin")
  override var pos by string("pos")
  override var rects by string("rects")
  override var regular by bool("regular")
  override var root by string("root")
  override var samplePoints by int("samplepoints")
  override var shape by enum<Shape>("shape")
  override var shapeFile by string("shapefile")
  override var showBoxes by int("showboxes")
  override var sides by int("sides")
  override var skew by number("skew")
  override var sortv by int("sortv")
  override var style by enum<NodeStyle>("style")
  override var target by string("target")
  override var tooltip by string("tooltip")
  override var url by string("URL")
  override var vertices by string("vertices")
  override var width by number("width")
  override var xlabel by string("xlabel")
  override var xlp by string("xlp")
  override var z by number("z")
}

internal class EdgeAttributesImpl(objects: ObjectFactory, providers: ProviderFactory) :
  EdgeAttributes,
  InternalPropertiesSpec by PropertiesSpecImpl(objects, providers, "atlas.graphviz.edge") {
  override var arrowHead by enum<ArrowType>("arrowhead")
  override var arrowSize by number("arrowsize")
  override var arrowTail by enum<ArrowType>("arrowtail")
  override var linkColor by string("color")
  override var colorScheme by string("colorscheme")
  override var comment by string("comment")
  override var constraint by bool("constraint")
  override var decorate by bool("decorate")
  override var dir by enum<Dir>("dir")
  override var edgeHref by string("edgehref")
  override var edgeTarget by string("edgetarget")
  override var edgeTooltip by string("edgetooltip")
  override var edgeUrl by string("edgeURL")
  override var fillColor by string("fillcolor")
  override var fontColor by string("fontcolor")
  override var fontName by string("fontname")
  override var fontSize by string("fontsize")
  override var headLp by string("head_lp")
  override var headClip by bool("headclip")
  override var headHref by string("headhref")
  override var headLabel by string("headlabel")
  override var headPort by string("headport")
  override var headTarget by string("headtarget")
  override var headTooltip by string("headtooltip")
  override var headUrl by string("headURL")
  override var href by string("href")
  override var id by string("id")
  override var label by string("label")
  override var labelAngle by number("labelangle")
  override var labelDistance by number("labeldistance")
  override var labelFloat by bool("labelfloat")
  override var labelFontColor by string("labelfontcolor")
  override var labelFontName by string("labelfontname")
  override var labelFontSize by string("labelfontsize")
  override var labelHref by string("labelhref")
  override var labelTarget by string("labeltarget")
  override var labelTooltip by string("labeltooltip")
  override var labelUrl by string("labelURL")
  override var layer by string("layer")
  override var len by number("len")
  override var lhead by string("lhead")
  override var lp by string("lp")
  override var ltail by string("ltail")
  override var minLen by int("minlen")
  override var noJustify by bool("nojustify")
  override var penWidth by number("penwidth")
  override var pos by string("pos")
  override var sameHead by string("samehead")
  override var sameTail by string("sametail")
  override var showBoxes by int("showboxes")
  override var linkStyle by enum<EdgeStyle>("style")
  override var tailLp by string("tail_lp")
  override var tailClip by bool("tailclip")
  override var tailHref by string("tailhref")
  override var tailLabel by string("taillabel")
  override var tailPort by string("tailport")
  override var tailTarget by string("tailtarget")
  override var tailTooltip by string("tailtooltip")
  override var tailUrl by string("tailURL")
  override var target by string("target")
  override var tooltip by string("tooltip")
  override var url by string("URL")
  override var weight by number("weight")
  override var xLabel by string("xlabel")
  override var xlp by string("xlp")
}

internal class GraphAttributesImpl(objects: ObjectFactory, providers: ProviderFactory) :
  GraphAttributes,
  InternalPropertiesSpec by PropertiesSpecImpl(objects, providers, "atlas.graphviz.graph") {
  override var background by string("_background")
  override var bb by string("bb")
  override var beautify by bool("beautify")
  override var bgColor by string("bgcolor")
  override var center by bool("center")
  override var charset by string("charset")
  override var clusterRank by enum<ClusterMode>("clusterrank")
  override var colorScheme by string("colorscheme")
  override var comment by string("comment")
  override var compound by bool("compound")
  override var concentrate by bool("concentrate")
  override var damping by float("Damping")
  override var defaultDist by number("defaultdist")
  override var dim by int("dim")
  override var dimen by int("dimen")
  override var dirEdgeConstraints by string("diredgeconstraints")
  override var dpi by number("dpi")
  override var epsilon by float("epsilon")
  override var esep by string("esep")
  override var fontColor by string("fontcolor")
  override var fontName by string("fontname")
  override var fontNames by string("fontnames")
  override var fontPath by string("fontpath")
  override var fontSize by string("fontsize")
  override var forceLabels by bool("forcelabels")
  override var gradientAngle by int("gradientangle")
  override var href by string("href")
  override var id by string("id")
  override var imagePath by string("imagepath")
  override var inputScale by number("inputscale")
  override var k by number("K")
  override var label by string("label")
  override var labelScheme by int("label_scheme")
  override var labelJust by string("labeljust")
  override var labelLoc by string("labelloc")
  override var landscape by bool("landscape")
  override var layerListSep by string("layerlistsep")
  override var layers by string("layers")
  override var layerSelect by string("layerselect")
  override var layerSep by string("layersep")
  override var layout by enum<LayoutEngine>("layout")
  override var levels by int("levels")
  override var levelsGap by number("levelsgap")
  override var lheight by number("lheight")
  override var lineLength by int("linelength")
  override var lp by string("lp")
  override var lWidth by number("lwidth")
  override var margin by string("margin")
  override var maxiter by int("maxiter")
  override var mcLimit by number("mclimit")
  override var minDist by number("mindist")
  override var mode by string("mode")
  override var model by string("model")
  override var newRank by bool("newrank")
  override var nodeSep by number("nodesep")
  override var noJustify by bool("nojustify")
  override var normalize by string("normalize")
  override var noTranslate by bool("notranslate")
  override var nsLimit by number("nslimit")
  override var nsLimit1 by number("nslimit1")
  override var oneBlock by bool("oneblock")
  override var ordering by string("ordering")
  override var orientation by number("orientation")
  override var outputOrder by string("outputorder")
  override var overlap by string("overlap")
  override var overlapScaling by number("overlap_scaling")
  override var overlapShrink by bool("overlap_shrink")
  override var pack by string("pack")
  override var packMode by string("packmode")
  override var pad by string("pad")
  override var page by string("page")
  override var pageDir by string("pagedir")
  override var quadTree by string("quadtree")
  override var quantum by number("quantum")
  override var rankDir by enum<RankDir>("rankdir")
  override var rankSep by number("ranksep")
  override var ratio by string("ratio")
  override var reminCross by bool("remincross")
  override var repulsiveForce by number("repulsiveforce")
  override var resolution by number("resolution")
  override var root by string("root")
  override var rotate by int("rotate")
  override var rotation by number("rotation")
  override var scale by string("scale")
  override var searchSize by int("searchsize")
  override var sep by string("sep")
  override var showBoxes by int("showboxes")
  override var size by string("size")
  override var smoothing by enum<SmoothType>("smoothing")
  override var sortv by int("sortv")
  override var splines by string("splines")
  override var start by string("start")
  override var style by string("style")
  override var styleSheet by string("stylesheet")
  override var target by string("target")
  override var tbBalance by string("TBbalance")
  override var tooltip by string("tooltip")
  override var trueColor by bool("truecolor")
  override var url by string("URL")
  override var viewPort by string("viewport")
  override var voroMargin by number("voro_margin")
  override var xdotVersion by string("xdotversion")
}

internal class ClusterAttributesImpl(objects: ObjectFactory, providers: ProviderFactory) :
  ClusterAttributes,
  InternalPropertiesSpec by PropertiesSpecImpl(objects, providers, "atlas.graphviz.cluster") {
  override var bgColor by string("bgcolor")
  override var fillColor by string("fillcolor")
  override var fontColor by string("fontcolor")
  override var fontName by string("fontname")
  override var fontSize by string("fontsize")
  override var labelJust by string("labeljust")
  override var labelLoc by string("labelloc")
  override var lineColor by string("color")
  override var margin by string("margin")
  override var penColor by string("pencolor")
  override var penWidth by number("penwidth")
  override var style by string("style")
}
